import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/layout/navbar";
import { LoadingProvider } from "./context/loaderContext";
import { ToastProvider } from "./context/ToastContext";
import Toast from "./components/customs/toast/Toast";
import Loader from "./components/customs/loader/loader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`flex flex-col justify-start items-center min-h-screen w-full bg-charade-950 font-sans ${geistSans.variable} ${geistMono.variable} antialiased`}>
      {/* <body className={`flex flex-col justify-start items-center min-h-screen w-full bg-gradient-to-b from-fuchsia-950 from-30% via-fuchsia-800 via-70% to-fuchsia-700 to-90% font-sans ${geistSans.variable} ${geistMono.variable} antialiased`}> */}
        <LoadingProvider>
            <ToastProvider>
                <Toast />
                <Loader />
                <Navbar/>
                {children}
              </ToastProvider>
            </LoadingProvider>
      </body>
    </html>
  );
}
